language: lisp
sudo: required

os:
  - linux
  - osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install sbcl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install zlib1g-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sbcl; fi
  - curl -O "https://beta.quicklisp.org/quicklisp.lisp"
  - sbcl --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install :path \"~/quicklisp\")"
  - sbcl --non-interactive --load ~/quicklisp/setup.lisp --eval "(ql::without-prompting (ql:add-to-init-file))"

script:
  - make cycle

before_deploy:
  - mv cycle "cycle-$TRAVIS_OS_NAME"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: cycle-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
