language: lisp
sudo: required

dist: xenial
os:
  - linux
  - osx

install:
  - ./ci/install.sh

script:
  - make cycle

before_deploy:
  - mv cycle "cycle-$TRAVIS_OS_NAME"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: cycle-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
