language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi

script:
  - sbcl --load "cycle.asd" --eval "(ql:quickload :cycle)" --eval "(sb-ext:save-lisp-and-die \"cycle\" :toplevel 'cycle:main :executable t)"

before_deploy: "mv cycle cycle-linux"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: "cycle"
  skip_cleanup: true
  on:
    tags: true
