language: python

python:
  - 3.7

dist: xenial

os:
  - linux
  - osx

install:
  - ./ci/install.sh
  - pip install -r requirements.txt

script:
  - make cycle

before_deploy:
  - mv cycle "cycle-$TRAVIS_OS_NAME"

deploy:
  provider: releases
  token: $GITHUB_OAUTH_TOKEN
  file: cycle-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
