language: lisp
sudo: required

os:
  - linux
  - osx

env:
  matrix:
    - LISP=sbcl

# either use a local install.sh script or install it via curl. Feel
# free to simplify this section in your own .travis.yml file.
install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install.sh; fi
    else
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh; fi
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sbcl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O "https://beta.quicklisp.org/quicklisp.lisp"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sbcl --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install :path \"~/quicklisp\")"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sbcl --non-interactive --load ~/quicklisp/setup.lisp --eval "(ql::without-prompting (ql:add-to-init-file))"; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sbcl --load "cycle.asd" --eval "(ql:quickload :cycle)" --eval "(sb-ext:save-lisp-and-die \"cycle\" :toplevel 'cycle:main :executable t)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make cycle; fi

before_deploy:
  - mv cycle "cycle-$TRAVIS_OS_NAME"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: cycle-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
